fiaisis/FIA-API

.github/dependabot.yml
.github/workflows/formatting.yml
.github/workflows/linting.yml
.github/workflows/tests.yml
.gitignore
.pylintrc
README.md
ir_api/ir_api.py
ir_api/scripts/acquisition.py
ir_api/scripts/script.py
main.py
mypy.ini
pyproject.toml
test/test_acquisition.py

Add initial API framework and basic first iteration of script acquisition
This does not include script transforms as there is already an issue open for this.

Add api framework

---

README.md
container/ir_api.D
pyproject.toml

Closes #4 
Creates the container and adds commands to the readme

Initial Container

---

.github/workflows/tests.yml
README.md
pyproject.toml

Closes #5 
Adds coverage and badge

Add coverage

---

.github/workflows/tests.yml
README.md
ir_api/core/model.py
ir_api/core/repositories.py
test/core/test_repositories_integration.py
test/test_e2e.py

Closes None as it's part of the deployment issue in the K8s repo
Changes necessary to make the API fit in with the Production database

Make IR-API fit the integration

---

ir_api/scripts/transforms/mari_transforms.py
test/scripts/transforms/test_mari_transforms.py
test/test_e2e.py

Closes #49 
Adds the permalink to the additional values to be substituted.

Substitute mask link

---

ir_api/scripts/transforms/mari_transforms.py
test/scripts/transforms/test_mari_transforms.py
test/test_e2e.py

Closes https://github.com/interactivereduction/run-detection/issues/106

Add wbvan transform

---

ir_api/core/repositories.py

pre ping the connection pool

---

ir_api/scripts/transforms/factory.py
ir_api/scripts/transforms/mari_transforms.py
ir_api/scripts/transforms/test_transforms.py
test/scripts/transforms/test_factory.py
test/test_e2e.py

closes #91  https://github.com/orgs/interactivereduction/projects/4?pane=issue&itemId=26759554
Uses test instrument in e2e

Use test instrument in e2e

---

ir_api/core/repositories.py
ir_api/scripts/acquisition.py
ir_api/scripts/transforms/factory.py
ir_api/scripts/transforms/mari_transforms.py

Closes #97 
Adds various new logging statements where I believe a significant application state has changed.

Add new logs

---

ir_api/core/model.py
ir_api/core/repositories.py
pyproject.toml

Enables the recycling and updates mypy while removing the ignores which are no longer needed.

Enable recycling and update sqlalchemy

---

README.md
codecov.yml
ir_api/core/model.py
pyproject.toml
utils/db_generator.py

Closes #136 
Adds script that can create the tables and populate them on an existing database called `interative-reduction`
You can verify by dropping with cascade all the tables and running the script on a local postgres.

Add db_generator_script

---

.github/workflows/formatting.yml
ir_api/core/model.py
test/test_e2e.py

Move black trigger

---

ir_api/core/exceptions.py
ir_api/core/responses.py
ir_api/core/utility.py
ir_api/exception_handlers.py
ir_api/ir_api.py
ir_api/router.py
ir_api/scripts/acquisition.py
test/core/test_utility.py
test/scripts/test_acquisition.py
test/test_e2e.py

Closes #13 
Implements the basic get script by hash. It adds the tests also. 
There is a TODO for when the other PR is in that will make this more efficient.

Add get by hash

---

.dockerignore
ir_api/router.py
test/e2e/test_core.py

Refs https://github.com/interactivereduction/gitops/pull/12

Add probes

---

.github/workflows/formatting.yml
.github/workflows/linting.yml
.github/workflows/tests.yml
container/ir_api.D
pyproject.toml

update python version

---

ir_api/scripts/acquisition.py
ir_api/scripts/transforms/mantid_transform.py
test/e2e/test_core.py
test/e2e/test_scripts.py
test/scripts/transforms/test_mantid_transform.py

Adds the github token and ensures that future imports are always first.

Add transform and apply

---

.github/workflows/build-and-push.yml

Part of an overarching long running issue of a lack of CD
All in the Github Workflow

Create initial CD prototype

---

fia_api/core/services/reduction.py
fia_api/core/specifications/reduction.py
fia_api/router.py
test/core/services/test_reduction.py
test/e2e/test_core.py

Closes #345
Adds endpoint to Get all reductions

Add new endpoint

---

README.md
fia_api/core/auth/api_keys.py
fia_api/core/model.py
fia_api/core/repositories.py
fia_api/core/services/instrument.py
fia_api/core/specifications/instrument.py
fia_api/router.py
pyproject.toml
test/core/services/test_instrument.py
test/core/test_repositories_integration.py
test/e2e/test_core.py
test/utils.py
utils/db_generator.py

Closes #355 
Adds API Key Auth - which needs a secret added to the cluster
Adds a way to get and update instrument specifications

Add spec endpoints

---

fia_api/scripts/transforms/osiris_transform.py
test/scripts/transforms/test_osiris_transform.py

Adjust osiris transform

---

fia_api/core/repositories.py
fia_api/router.py
test/core/test_repositories_integration.py
test/e2e/test_core.py

Closes None
Related
https://github.com/fiaisis/gitops/pull/51

Test db on ready

---

fia_api/scripts/transforms/factory.py
fia_api/scripts/transforms/loq_transform.py
test/scripts/transforms/test_loq_transforms.py
test/scripts/transforms/test_mari_transforms.py

Closes None, part of the Epic https://github.com/fiaisis/planning/issues/25
Add LOQ script transform

Add loq script transform support

---

.github/workflows/tests.yml
fia_api/core/utility.py
fia_api/router.py
test/core/test_utility.py
test/e2e/test_core.py

Adds an endpoint that fetches Mantid package versions from GitHub

Add Mantid versions endpoint

---

fia_api/scripts/transforms/loq_transform.py
test/scripts/transforms/test_loq_transforms.py

Closes None, required for the LOQ rundetection rule changes
Now need to support optional variable changes in the API which is in line with the changes to the rundetection LOQ rules

LOQ transform now with optionals

---

fia_api/scripts/transforms/loq_transform.py
test/scripts/transforms/test_loq_transforms.py

Part of: https://github.com/fiaisis/run-detection/issues/345
Add a transform for the script, extremely simple.

Add support for custom slice wavs for LOQ

---

fia_api/scripts/transforms/loq_transform.py
test/scripts/transforms/test_loq_transforms.py

Closes None, part of this work: https://github.com/fiaisis/run-detection/issues/346
The API side of the new run-detection rule for adding Phi Limits

Add transform for LOQ setting Phi Limits via rules

---

fia_api/scripts/transforms/factory.py
fia_api/scripts/transforms/sans_transform.py
test/scripts/transforms/test_factory.py
test/scripts/transforms/test_loq_transforms.py
test/scripts/transforms/test_sans2d_transforms.py

Closes https://github.com/fiaisis/planning/issues/30
Add SANs2D script transform by refactoring the LOQ one to be a generic sans transform.

Sans2d script transform

---

fia_api/scripts/transforms/factory.py
fia_api/scripts/transforms/vesuvio_transform.py
test/scripts/transforms/test_factory.py
test/scripts/transforms/test_vesuvio_transforms.py

Closes [#463](https://github.com/fiaisis/FIA-API/issues/463)
Add the vesuvio transforms

Vesuvio transforms

---

fia_api/core/request_models.py
fia_api/core/responses.py
fia_api/core/services/job.py
fia_api/routers/extras.py
fia_api/routers/find_file.py
fia_api/routers/jobs.py
test/core/services/test_job.py

Closes None
This allows partial updates without the job watcher needing to specify the entire object everytime

Allow partial updates

---

.github/workflows/build-and-push.yml
fia_api/core/auth/tokens.py
fia_api/core/exceptions.py
fia_api/core/job_maker.py
fia_api/core/repositories.py
fia_api/core/services/job.py
fia_api/core/specifications/job_owner.py
fia_api/core/specifications/script.py
fia_api/exception_handlers.py
fia_api/fia_api.py
fia_api/routers/job_creation.py
fia_api/routers/jobs.py
fia_api/scripts/acquisition.py
test/core/test_job_maker.py
test/core/test_repositories_integration.py
test/e2e/test_core.py
test/e2e/test_job_maker.py
test/e2e/test_scripts.py
test/scripts/test_acquisition.py
test/scripts/transforms/test_iris_transform.py
test/scripts/transforms/test_osiris_transform.py

Closes None.
Adds staff permission bypass.

Bypass download permissions as staff

---

fia_api/core/request_models.py

Only accept str

---

fia_api/exception_handlers.py
fia_api/fia_api.py
test/e2e/test_scripts.py

Closes None, noticed in staging/prod
Actually written by @keiranjprice101 I am just cleaning up the git history a little.

Add handler for validation exceptions with logging

---

.github/workflows/tests.yml
fia_api/core/auth/tokens.py
fia_api/core/exceptions.py
fia_api/core/models.py
fia_api/core/request_models.py
fia_api/core/services/job.py
fia_api/fia_api.py
fia_api/routers/extras.py
fia_api/routers/live_data.py
fia_api/scripts/live_data.py
pyproject.toml
test/core/services/test_job.py
test/e2e/test_live_data_script.py

Original PR was approved, but not ready for merge.
Keeping this in the meantime
Reverts fiaisis/FIA-API#498

Revert "Revert "Add live data script putting""

---

fia_api/scripts/transforms/enginx_transform.py
fia_api/scripts/transforms/factory.py
test/e2e/test_live_data_script.py
test/scripts/transforms/test_enginx_transform.py
test/scripts/transforms/test_factory.py

Add the initial engin x transofmr. And enable a pytest skip
refs https://github.com/fiaisis/FIA-API/issues/522

Initial enginx
